name: cuneiform
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.6.1
  path_provider: ^2.1.5
  http: ^1.1.0  # Add this line
  lucide_icons: ^0.257.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.5.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/icon.png"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
